package linksawakening.gameplay;

public enum GameplaySoundEvent {
    ROC_FEATHER_JUMP,
    PIT_FALL,
    SWORD_SWING_A,
    SWORD_SWING_B,
    SWORD_SWING_C,
    SWORD_SWING_D,
    SWORD_FULLY_CHARGED,
    SPIN_ATTACK,
    CUT_GRASS,
    INVENTORY_OPEN,
    INVENTORY_CLOSE,
    MENU_MOVE,
    MENU_VALIDATE,
    SHIELD_TING,
    LINK_HURT,
    ENEMY_BUMP,
    ENEMY_HIT,
    SWORD_POKE,
    ENEMY_BURNING,
    ENEMY_DESTROYED,
    BEAMOS_LASER,
    SPIKE_TRAP_WHOOSH,
    WRONG_ANSWER,
    DOOR_UNLOCKED
}
